### ISSUE TITLE
[Bug] Layout AutoSwitching not occurring on instance change

### ISSUE THREAD

**Issue by WadeWilsonWannabe** [Krealle/Cell_UnitFrames#179]
### Addon Version

1.4.11

### World of Warcraft Version

Retail

### Describe the bug

I have the Master Layout set to None. When I go into an instance (dungeon) the party layout shows, but it also has a Player Unit frame loaded when it is not enabled in the Party Layout. If I open cell and go to the Layouts tab, the Player Unit Frame is removed like it should be and will stay gone while in the instance.
Once I leave the instance/party, the Cell Layout switches back to my Solo layout, but there is no Player Unit Frame even though it is enabled in this layout. Again, if I go into the Cell options and the Layout tab, the Player Unit Frame will show again.

### Steps to reproduce

Join a party and go into dungeon instance, Open Cell Options and go to layout tab.

Party Layout has the Player Unit frame disabled, Solo has it enabled.

### BugSack

```bash
nothing showing in BugSack when this bug occurs.
```

**Comment by Krealle** [comment]
This should be resolved, with the next update.

**Comment by WadeWilsonWannabe** [comment]
I was going through the code, and trying to learn, would love to know how you solved it if you ever find the time.

**Comment by Krealle** [comment]
You can see the fix here: https://github.com/Krealle/Cell_UnitFrames/commit/11a74461246424736a019ffe6f8ea40f9263ccf0

Simply didn't update my vars properly.

**Comment by WadeWilsonWannabe** [comment]
This issue is still present even after update as well as uninstall and reinstall. Must open the Cell Layouts tab for the layout to appropriately update.

**Comment by Krealle** [comment]
Pushing a new fix, should be resolved now.
